reload_integration:
  name: "Reload integration"
  description: "Reloading the integration."
  fields:
    dummy_field:
      name: "Dummy Field"
      description: "A placeholder field for reloading the integration."
